//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAula4MVC.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoAula4MVC_DBEntities : DbContext
    {
        public ProyectoAula4MVC_DBEntities()
            : base("name=ProyectoAula4MVC_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Departamentos_Idea> Departamentos_Idea { get; set; }
        public virtual DbSet<Herramientas4RI> Herramientas4RI { get; set; }
        public virtual DbSet<Ideas_De_Negocio> Ideas_De_Negocio { get; set; }
        public virtual DbSet<Impactos> Impactos { get; set; }
        public virtual DbSet<Integrantes> Integrantes { get; set; }
    }
}
