//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAula4MVC.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos_Idea
    {
        public int ID_Departamentos_Idea { get; set; }
        public int ID_Idea { get; set; }
        public int ID_Departamento { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Ideas_De_Negocio Ideas_De_Negocio { get; set; }
    }
}
