//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAula4MVC.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ideas_De_Negocio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ideas_De_Negocio()
        {
            this.Departamentos_Idea = new HashSet<Departamentos_Idea>();
            this.Integrantes = new HashSet<Integrantes>();
        }
    
        public int ID_Idea { get; set; }
        public string Nombre { get; set; }
        public int ID_Impacto { get; set; }
        public decimal Valor_Inversion { get; set; }
        public decimal Valor_Inversion_Infraestructura { get; set; }
        public decimal Total_Ingresos { get; set; }
        public int ID_Herramienta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamentos_Idea> Departamentos_Idea { get; set; }
        public virtual Herramientas4RI Herramientas4RI { get; set; }
        public virtual Impactos Impactos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Integrantes> Integrantes { get; set; }
    }
}
