//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAula4MVC.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integrantes
    {
        public int ID_Integrante { get; set; }
        public int ID_Idea { get; set; }
        public int NumIdentificacion { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Rol { get; set; }
        public string Email { get; set; }
    
        public virtual Ideas_De_Negocio Ideas_De_Negocio { get; set; }
    }
}
